# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
   - index.md
   - about.md

# footer: 

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

name: Escupitajo

description: Puaajjjj

plugins:
  - jekyll-seo-tag
